name: tidewallet3
description: TideWallet 3.0 - The Wallet Protect Your Assets

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  intl: ^0.16.1

  # UI
  # barcode_scan: ^3.0.1
  custom_radio_grouped_button: ^1.0.6+1
  decimal: ^0.3.5
  url_launcher: ^5.7.10

  # Bloc
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1

  equatable: ^1.2.5
  
  rxdart: ^0.25.0
  qr_code_scanner: ^0.3.0
  qr_flutter: ^3.2.0
  image_gallery_saver: ^1.6.7
  permission_handler: ^5.0.1+1
  logger: ^0.9.4
  dio: ^3.0.10
  shared_preferences: ^0.5.12+4
  # socket_io_client: ^0.9.12
  web_socket_channel: ^1.2.0

  #db
  sqflite: ^1.3.2+2
  floor: ^0.18.0

  # crypto
  web3dart: ^1.2.3
  bip32: ^1.0.6
  sha3: ^0.1.2
  encrypt: ^4.0.3
  # bitcoin
  bs58check: ^1.0.1
  bitcoins: ^1.0.5
  bitcoin_flutter: ^2.0.2
  # bitcoin cash
  bitbox: ^0.0.5
  # hash
  bird_cryptography: ^0.0.1+2
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  alice: ^0.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  floor_generator: ^0.18.0
  flutter_launcher_icons: ^0.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icon/icon_android.png"
  image_path_ios: "assets/icon/icon_ios.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - locale/en.json
    # - sql/
    - assets/images/
    - assets/images/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
